name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt update && apt install -y \
          git zip unzip openjdk-11-jdk \
          python3-pip python3-dev build-essential \
          libffi-dev libssl-dev libsqlite3-dev \
          zlib1g-dev libncurses5-dev libncursesw5-dev \
          libreadline-dev libgdbm-dev libc6-dev \
          libbz2-dev liblzma-dev libxml2-dev \
          libxslt-dev libjpeg-dev libfreetype6-dev

    - name: Install buildozer
      run: |
        pip3 install --upgrade pip setuptools wheel
        pip3 install cython
        pip3 install buildozer

    - name: Create buildozer.spec if missing
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Update buildozer.spec
      run: |
        sed -i 's/^requirements = .*/requirements = python3,kivy,kivymd/' buildozer.spec
        sed -i 's|^# entrypoint = main.py|entrypoint = main.py|' buildozer.spec
        sed -i 's/^# android.api =.*/android.api = 31/' buildozer.spec
        sed -i 's/^# android.ndk =.*/android.ndk = 23b/' buildozer.spec
        sed -i 's/^# android.archs =.*/android.archs = arm64-v8a,armeabi-v7a/' buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyCalcApp-APK
        path: bin/*.apk
