name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-dev openjdk-11-jdk zip unzip wget

    - name: Install Python and Buildozer
      run: |
        python3 -m pip install --upgrade pip setuptools wheel cython
        pip install buildozer

    - name: Accept Android SDK licenses and install build-tools
      run: |
        mkdir -p ~/.android
        echo '### Accepted licenses ###' > ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true
        sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Configure buildozer.spec
      run: |
        sed -i 's/^requirements = .*/requirements = python3,kivy,kivymd/' buildozer.spec || true
        sed -i 's/^# *entrypoint = .*/entrypoint = main.py/' buildozer.spec || true

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
