name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer & Dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install cython
        pip install buildozer

    - name: Initialize buildozer if not exists
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Configure buildozer.spec
      run: |
        sed -i 's/^requirements = .*/requirements = python3,kivy,kivymd/' buildozer.spec
        sed -i 's|^# entrypoint = main.py|entrypoint = main.py|' buildozer.spec
        sed -i 's/^# android.api =.*/android.api = 31/' buildozer.spec
        sed -i 's/^# android.ndk =.*/android.ndk = 23b/' buildozer.spec
        sed -i 's/^# android.archs =.*/android.archs = arm64-v8a,armeabi-v7a/' buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyCalcApp-APK
        path: bin/*.apk
