name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install system packages
      run: sudo apt-get update && sudo apt-get install -y build-essential git python3-dev openjdk-11-jdk zip unzip wget

    - name: Install Python and Buildozer
      run: |
        python3 -m pip install --upgrade pip setuptools wheel cython
        pip install buildozer

    - name: Configure buildozer.spec
      run: |
        sed
