name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-dev openjdk-11-jdk zip unzip wget

    - name: Install Python and Buildozer
      run: |
        python3 -m pip install --upgrade pip setuptools wheel cython
        pip install buildozer

    - name: Install Android SDK Command Line Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Configure buildozer.spec
      run: |
        sed -i 's/^requirements = .*/requirements = python3,kivy,kivymd/' buildozer.spec || true
        sed -i 's/^# *entrypoint = .*/entrypoint = main.py/' buildozer.spec || true

    - name: Build APK
      env:
        ANDROID_HOME: $HOME/android-sdk
        PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
