name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment and Build APK
      env:
        ANDROID_HOME: $HOME/android-sdk
        PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/.local/bin:$PATH
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk python3-pip python3-dev
        python3 -m pip install --upgrade pip setuptools wheel cython
        pip install buildozer
        buildozer init
        sed -i 's/^requirements = .*/requirements = python3,kivy,kivymd/' buildozer.spec
        sed -i 's/^# *entrypoint =.*/entrypoint = main.py/' buildozer.spec
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
